### ISSUE TITLE
[BUG] Crashing when cutting down trees (1.30 world on 1.31)

### ISSUE THREAD

**Issue by classicduff** [TCreopargh/GreedyCraft#115] opened 2021-02-14 01:30 UTC
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
Crashing when chopping down a tree with tinker's construct lumberaxe, but I've had it happen with a normal tinkers construct axe too.

**To Reproduce**
1. Go to a 1.30 world loaded in 1.31
2. Start chopping down trees in a maple forest with a lumberaxe (i think it happend once using a regular axe too though)
3. ???
4. Occasional crashing requiring game restart

**Crash reports or logs**
**[Crash Log](https://drive.google.com/file/d/11INgXI2dw0gG0w6HZHkpzZVch3KEwEBk/view?usp=sharing)**

**Details**
Please fill out the blanks below:
Modpack Version: (GreedyCraft-1.31.0.109.1 )
Did you add or remove mods? (No)
Did you edit any config or script? (No )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  (Default)
Singleplayer, LAN game or server pack? ( Single Player)

**Additional context**
World was originally made on GreedyCraft-1.30.1.107.1

`java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=check_decay, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=sakura:umeleaves, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer`
^ may or may not be the main error.

**Comment by TCreopargh** [comment] 2021-02-14 01:31
Please provide your crash report in another way, this link says that I don't have permission

**Comment by TCreopargh** [comment] 2021-02-14 01:33
It's a duplicate of #105 , please follow the solution in that issue.

**Closed as completed by TCreopargh** 2021-02-14 01:33 UTC
Labels: bug
