### ISSUE TITLE
Game black screens after loading into world [BUG]

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [TCreopargh/GreedyCraft#161] opened 2021-03-28 07:01 UTC
**Before reporting, make sure your problem isn't caused by the game running out of RAM and you have read the installation guide carefully.**
If the game crashes to your desktop without showing a crash screen it's a RAM issue. Don't submit this kind of issue. Please view the installation guide for how to solve this issue. 
If this is not the case check the checkbox below by replacing the space between brackets with an 'x'.
 - [x] Yes, I'm sure this problem isn't because my game ran out of RAM.

**Describe the bug**
When loading into my world from the previous update, the screen turns black and I can no longer interact with the game. I get the following error in the log:

[02:41:52] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_281]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_281]
	at meldexun.entityculling.plugin.EntityCullingRenderer.updateEntityCullingState(EntityCullingRenderer.java:305) ~[EntityCulling-1.12.2-4.0.5.jar:?]
	at meldexun.entityculling.plugin.EntityCullingRendererOptifine.renderEntities(EntityCullingRendererOptifine.java:80) ~[EntityCulling-1.12.2-4.0.5.jar:?]
	at meldexun.entityculling.plugin.Hook.renderEntities(Hook.java:46) ~[EntityCulling-1.12.2-4.0.5.jar:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:805) ~[buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1808) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1621) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1390) ~[buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[02:41:52] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[02:41:52] [Client thread/ERROR] [minecraft/Minecraft]: @ VanillaFix GUI Loop
[02:41:52] [Client thread/ERROR] [minecraft/Minecraft]: 1280: Invalid enum

**To Reproduce**
Load into my world from a previous update. Cause is unknown.

**Expected behavior**
Black screens should not occur.

**Details**
Please fill out the blanks below:
Modpack Version: ( 1.34.0 updated from 1.33.1 )
Did you add or remove mods? ( No )
Did you edit any config or script? ( No )
Using shaders? [Write 'Default' if you are using default shader, if you are not using the default shader please write the name of the shader you are using.]  ( Default )
Singleplayer, LAN game or server pack? ( Singleplayer )

**Comment by TCreopargh** [comment] 2021-03-28 07:03
Duplicate of https://github.com/TCreopargh/GreedyCraft/issues/157, try the solutions there

**Closed as completed by TCreopargh** 2021-03-28 07:03 UTC
Labels: bug
